version: '3.6'

services:
  python-app:
    container_name: python-app
    build:
      context: ./python-app
    volumes:
      - $HOME/.aws/:/root/.aws/
    ports:
      - '9000:8080'
    env_file:
      - .env
    command:
      - app.lambda_handler
